### PR TITLE
Remove 'stopwatches' directory

### PR DESCRIPTION
**Pull request by mclow**
Vicente said (May 16th) that "I'm really sorry for that. Boost.Chrono/Stopwatches was never released even if it was included in the Boost repository" and "I'll remove it definitively from the boost repository."

### CODE REVIEW

**Comment by Lastique** [comment]
Note that stopwatches are referenced in https://github.com/boostorg/chrono/blob/develop/test/cycle_count.hpp, https://github.com/boostorg/chrono/blob/develop/example/chrono_accuracy_test.cpp#L14 and https://github.com/boostorg/thread/blob/develop/example/perf_condition_variable.cpp#L14. Also, there are stopwatches-related bits in https://github.com/boostorg/chrono/blob/develop/meta/libraries.json and https://github.com/boostorg/chrono/blob/develop/doc/chrono.qbk. These places need to be cleaned up as well.

**Comment by viboes** [comment]
Yes, this need a more careful cleanup.

**Comment by viboes** [comment]
I'm taking care of removing all the adherence to stopwatches folder.

**Comment by mclow** [comment]
> I'm taking care of removing all the adherence to stopwatches folder.

In that case, I will close this P/R.

**Comment by viboes** [comment]
Hi,

I've just merged this

https://github.com/boostorg/chrono/commit/ce6286ae6eca8531f79c58745a7e1c83ebdc120f

Marshall,I had some troubles with my quickbook installation and I was unable to check the doc changes. Please, could you check that doc generation has not been broken?

Thanks for recall me to do this due cleanup.

**Pull request closed without merging**
